version: '3.1'

services:
  db:
    image: postgres:13.13-alpine3.19
    container_name: postgres
    environment:
      POSTGRES_DB: local-trending
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    hostname: db
  local-trending:
    image: local-trending
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    container_name: local-trending
    ports:
      - "8080:8080"
    env_file: "local.env"
    volumes:
      - ./config/local.yaml:/config/config.yaml
      - ./migrations:/config/migrations
    command: video-ingest --conf /config/config.yaml
    restart: always
    depends_on:
      - "db"